### ISSUE TITLE
Unable to install helix-editor/helix on Intel macOS

### ISSUE THREAD

**Issue by DannyJJK** [houseabsolute/ubi#24]
[Helix](https://github.com/helix-editor/helix) is becoming a popular editor built in Rust, so it would be nice for this to be supported. It does have the platform on the releases, but I guess it's in a different format to what's expected. I ran the following command:
`ubi -p helix-editor/helix -i /usr/local/bin`

And it gave me this error:
`[ubi][ERROR] could not find a release for this OS and architecture from helix-22.08.1-aarch64-macos.tar.xz, helix-22.08.1-source.tar.xz, helix-22.08.1-x86_64-linux.tar.xz, helix-22.08.1-x86_64-macos.tar.xz, helix-22.08.1-x86_64-windows.zip, helix-22.08.1-x86_64.AppImage, helix-22.08.1-x86_64.AppImage.zsync`

My architecture is Intel macOS (sometimes written as darwin x86_64)
ubi 0.0.16

**Comment by autarch** [comment]
Thanks for the bug report! This is fixed in v0.0.17.

That said, you'll still need to pass `--exe hx` to `ubi` since the executable is not named `helix`. Also, it seems like the helix releases have a bunch of other non-executable files in them. Those will be ignored by `ubi`, so if those are important then `ubi` probably isn't the best tool here.

**Comment by DannyJJK** [comment]
I've confirmed this now works on ubi v0.0.17 when using the --exe option.
